RuntimeError: The 'SECRET_KEY' setting has been removed. Please refer to 'https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html' for available settings.