Revert "Fixing: AttributeError: 'UsersTablePage' object has no attribute 'assert_change_password_is_loaded'"
This reverts commit 359e1b68e6b54c2500434116b8abf7bdaf9b9322.