Revert "Fixing: AttributeError: 'UsersTablePage' object has no attribute 'assert_change_password_is_loaded'"
This reverts commit 7ea644948fbd24a84d9bf3dfad9858f42297ffc8.