Revert "Fixing: AttributeError: 'UsersTablePage' object has no attribute 'assert_change_password_is_loaded'"
This reverts commit 06024b69b0731ed976dbe543771dfc1b3c4826d7.