Revert "Fixing: AttributeError: 'ProfileEditPage' object has no attribute 'assert_error_shown'. Did you mean: 'assert_error_visible'?"
This reverts commit ba989e327cbe485a1e048c71e7e1cfa8a98a17fd.